spring:
  datasource:
    url: jdbc:h2:mem:booking
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: 8081

booking:
  database:
    server:
      port: 9090