version: '3.4'

services:

  rabbit:
    image: rabbitmq:3-management
    container_name: booking-rabbit
    ports:
      - '15672:15672'

  db:
    image: booking/database:latest
    container_name: booking-db
    ports:
      - '8081:8081'

  producer-service:
    image: booking/producer-service:latest
    container_name: booking-producer
    depends_on:
      - db
      - rabbit
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://db:9090/mem:booking
      - SPRING_RABBITMQ_HOST=rabbit

  consumer-service:
    image: booking/consumer-service:latest
    container_name: booking-consumer
    depends_on:
      - db
      - rabbit
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://db:9090/mem:booking
      - SPRING_RABBITMQ_HOST=rabbit
