spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:booking
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /api-docs.yml

logging:
  level:
    org.zalando.logbook: TRACE
logbook:
  write:
    max-body-size: 100